version: '3'

services:
  mysql:
    image: mysql:8.0
    hostname: db_mysql
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - fed-common

  hospital:
    build:
      context: .
      dockerfile: ./IdP1/hospital/Dockerfile
    hostname: hp
    expose:
      - "80"
    depends_on:
      - mysql
    networks:
      - fed-common

  card:
    build:
      context: .
      dockerfile: ./IdP2/card/Dockerfile
    hostname: card
    expose:
      - "80"
    depends_on:
      - mysql
    networks:
      - fed-common

  insurance:
    build:
      context: .
      dockerfile: DP/insurance/Dockerfile
    hostname: is
    expose:
      - "80"
    depends_on:
      - mysql
    networks:
      - fed-common

  lg:
    build:
      context: .
      dockerfile: DP/lg/Dockerfile
    hostname: lg
    expose:
      - "80"
    depends_on:
      - mysql
    networks:
      - fed-common

  fed:
    build:
      context: .
      dockerfile: ./fed/Dockerfile
    hostname: fed
    expose:
      - "80"
    depends_on:
      - mysql
    networks:
      - fed-common

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker-entrypoint.d/50-self-signed-certificate.sh:/docker-entrypoint.d/50-self-signed-certificate.sh
    restart: always
    depends_on:
      - mysql
      - fed
      - hospital
      - lg
      - insurance
      - card
    networks:
      - fed-common

networks:
  fed-common:
    external: true

