FROM php:7.4-apache
#ADD ../simplesamlphp-1.19.5.tar.gz /var/
#RUN mv /var/simplesamlphp-1.19.5 /var/simplesamlphp
#ADD ../IdP2/card/simplesamlphp /var/simplesamlphp
#RUN chown -R www-data:www-data /var/simplesamlphp
ADD ../IdP2/card/www/html /var/www/html
RUN chown -R www-data:www-data /var/www/html